version: "3"

services:
  db:
    image: postgres
    env_file:
      - ./db/.env
    volumes:
      - ./db/data:/var/lib/postgres/data


  backend:
    image: 869809771819.dkr.ecr.ap-south-1.amazonaws.com/truck-booking
    command: gunicorn main.wsgi:application --bind 0.0.0.0:8000 --access-logfile gunicorn.log --error-logfile gunicornerr.log
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./backend/.env
    environment:
      - DEBUG=0
      - GOOGLE_APPLICATION_CREDENTIALS=/usr/src/app/firebase-admin.json


  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./web/nginx-proxy.prod.conf:/etc/nginx/conf.d/default.conf
      - ./backend/staticfiles:/staticfiles
      - ./backend/mediafiles:/mediafiles
    depends_on:
      - backend

volumes:
  db:
