# Generated by Django 3.2.7 on 2021-09-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0002_auto_20210921_1917")]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="is_verified",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="driver",
            name="is_verified",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
