# Generated by Django 3.2.7 on 2021-09-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0004_auto_20210921_2001")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, db_index=True, max_length=254, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                db_index=True, default="00000000", max_length=20, unique=True
            ),
            preserve_default=False,
        ),
    ]
